url: https://scc-digitalhub.github.io
baseurl: /scc-digitalhub/

# Site settings
title: Digital Hub
email: your-email@domain.com
description: "An Open Source Platform for Digital Transformation, Open Data and Open Service Management"


# Team names, titles and social links
people:
- name: Raman Kazhamiakin
  pic: https://my.fbk.eu/fbk-api/v2/picture/raman
  position: CTO, SCC Lab, FBK
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Albana Celepija
  pic: https://my.fbk.eu/fbk-api/v2/picture/acelepija
  position: Software Developer, SCC Lab, FBK
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Matteo Chini
  pic: https://my.fbk.eu/fbk-api/v2/picture/m.chini
  position: Software Developer, SCC Lab, FBK
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Fabio Fais
  pic: https://my.fbk.eu/fbk-api/v2/picture/ffais
  position: DevOps, SCC Lab, FBK
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Nawaz Khurshid
  pic: https://my.fbk.eu/fbk-api/v2/picture/khurshid
  position: Software Engineer, SCC Lab, FBK
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Matteo Martini
  pic: https://my.fbk.eu/fbk-api/v2/picture/mmartini
  position: Data Scientist, SCC Lab, FBK
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Michele Nori
  pic: https://my.fbk.eu/fbk-api/v2/picture/nori
  position: Software Architect, SCC Lab, FBK
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Matteo Saloni
  pic: https://my.fbk.eu/fbk-api/v2/picture/msaloni
  position: Software Architect, SCC Lab, FBK
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Erica Tomaselli
  pic: https://my.fbk.eu/fbk-api/v2/picture/ertomaselli
  position: Software Engineer, Dedagroup spa
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Alberto Carotti
  pic: https://my.fbk.eu/fbk-api/v2/picture/acarotti
  position: Software Engineer, Dedagroup spa
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty